- CHANGELOG.rst
- flask_dance/consumer/__init__.py
- flask_dance/consumer/requests.py
- tests/consumer/test_requests.py
To properly fix the bug identified in #12. Unfortunately, the `OAuth1Session` tests fail on the current version of requests-oauthlib (0.4.2), because it still contains the bug fixed by https://github.com/requests/requests-oauthlib/commit/b94f16472d66f5ed0febb8c1985854f379f7bac3.
> Make the `authorized` property load the token from the backend

- CHANGELOG.rst
- flask_dance/consumer/oauth2.py
- tests/consumer/test_oauth2.py
When experimenting with Facebook I became frustrated because I misconfigured my app
Had I been observant I would have noticed the error message in the URL. But I was looking at flasks debug message which was useless. So I ended up digging into the source. Not to mention I am not fluent in URL encoding
To prevent me or others from needing to do this again I wrapped the error up in a way that displays in the browser stack trace
I addressed the comments and obvious sloppiness from the previous PR. Specifically the test should work with any complaint python interpreter and I modify and reraise the original exception rather than making a new one
*im assuming that you still want python 2 support so I did not use exception chaining*
> Bubble up the params that caused a MissingTokenError

- CHANGELOG.rst
- docs/providers.rst
- flask_dance/contrib/facebook.py
- tests/contrib/test_facebook.py
Facebook is super popular! Like, at least 10 people on it. 
They also provide OAUTH! So I followed the Github blueprint and made a Facebook one. 
Tests pass, ill let you pep8 it :-P
Here is the app I wrote to test it 
```python
from flask import Flask, redirect, url_for
from flask_dance.contrib.facebook import make_facebook_blueprint, facebook
app = Flask(__name__)
app.secret_key = "SOSECRET"
blueprint = make_facebook_blueprint(
client_id="1386968274964921",
client_secret="dae4975ded05aadbbda82f5ae9477d9d",
)
app.register_blueprint(blueprint, url_prefix="/login")
@app.route("/")
def index():
if not facebook.authorized:
return redirect(url_for("facebook.login"))
resp = facebook.get("me")
assert resp.ok
return resp.text
if __name__ == "__main__":
app.run()
```
and a screenshot of the output
> add facebook provider

- CHANGELOG.rst
- flask_dance/consumer/oauth2.py
- tests/consumer/test_oauth2.py
If the user hits the ``authorized`` view without having a "state" variable set in the browser cookies, Flask-Dance will now redirect the user back to the ``login`` view to start the OAuth dance all over again, rather than raising a ``KeyError``. Fixes #34.
@rmoorman, can you take a look at this, and test it before it gets merged?
> If missing "state" variable, redirect to `login` view

- flask_dance/consumer/base.py
- tests/consumer/test_requests.py
`pkg_resources.parse_version()` is more flexible. Fixes #53.
@ThiefMaster, can you try this out and let me know if it works for you?
> `pkg_resources.parse_version()` instead of `distutils.StrictVersion`

- CHANGELOG.rst
- flask_dance/contrib/google.py
The google blueprint is not setting the auto_refresh_token_url. So the token is not automatically refreshing when it has expired and a valid refresh token exists.
As per: https://github.com/requests/requests-oauthlib/blob/master/docs/oauth2_workflow.rst#third-recommended-define-automatic-token-refresh-and-update
> add auto_refresh_url to oauth blueprint creation

- flask_dance/utils.py
My machine was set on UTC+7.
When the **value** of `dt` in `timestamp_from_datetime(dt)` is in UTC, such as in https://github.com/singingwolfboy/flask-dance/blob/deab6261c68e7eb643b0c174a9f4f0dd873d8316/flask_dance/consumer/base.py#L113
The function will treat `dt` as it is in UTC+7.
For example, when `dt = datetime.utcnow()` and `dt` becomes "2017-01-01 00:00:00.000", `dt.timestamp()` will convert `dt` to UNIX timestamp while assuming "2017-01-01 00:00:00.000" as UTC+7
> timezone handling in timestamp_from_datetime

- flask_dance/contrib/nylas.py
- tests/contrib/test_nylas.py
This change is not backwards compatible, but this feature was introduced so recently that I'm not worried about breaking other people's projects.
> Nylas wants to use 'client ID' and 'client secret'

- CHANGELOG.rst
- dev-requirements.txt
- docs/conf.py
It was rolled into Sphinx itself as of version 1.3. Fixes #80.
> Drop dependency on sphinxcontrib-napoleon

- CHANGELOG.rst
- README.rst
- docs/providers.rst
- flask_dance/contrib/discord.py
- tests/contrib/test_discord.py
I found Flask-Dance to be the most straightforward Flask's OAuth lib so far, hence I would like to bring my contribution to it by adding the Discord provider that I use in my own projects.
Feel free to let me know if I need to edit some other things to comply with your merging requirements.
> Add Discord provider

- CHANGELOG.rst
- flask_dance/consumer/backend/sqla.py
- flask_dance/consumer/oauth2.py
- tests/consumer/storage/test_sqla.py
This resolves the issue raised in #88, where Flask-Dance should have raised an exception instead of trying to create an OAuth token without an associated user. This changes the SQLAlchemy backend to take a new optional argument: `require_user`. When set to True, the backend will not allow OAuth tokens to be created without an associated user. This argument is True by default when an argument is passed for `user` or `user_id`.
@NathanWailes, can you take a look at this, and let me know if the functionality is what you had in mind?
> Make sqla backend know when to require a user

- CHANGELOG.rst
- flask_dance/consumer/requests.py
- tests/consumer/test_requests.py
Fixes #104. While investing that issue, I discovered that accessing the `access_token` property on an instance of the `OAuth2Session` class would only [attempt to locate an OAuth token on the client of the instance itself](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py#L116-L118), rather than querying the token backend.
Now, the `OAuth2Session` class defines its own `access_token` property that is aware of the token backend, and will use that backend instead of the client on the instance.
@giocalitri, can you test this out and let me know if it fixes your problem?
> Fetch access_token from backend

- CHANGELOG.rst
- README.rst
- dev-requirements.txt
- docs/backends.rst
- tests/consumer/storage/test_sqla.py
Flask-Cache is deprecated and unsupported, so we're moving to Flask-Caching instead.
> Flask-Caching

- CHANGELOG.rst
- flask_dance/consumer/oauth1.py
- flask_dance/consumer/requests.py
- tests/consumer/test_requests.py
I need to think about why this change is necessary for OAuth 1, but not for OAuth 2. The protocols are different; maybe the fact that OAuth 1 needs to do a consumer-to-provider request before redirecting the user means that trying to load the token so early in the process is simply doomed to failure? Or perhaps there's a better way of solving this problem...
Related to #120.
> Don't load token prematurely for OAuth1

- CHANGELOG.rst
- flask_dance/consumer/oauth1.py
- tests/consumer/test_oauth1.py
When entered Twitter Oauth page and clicked"Cancel" instead of "Authorize app", Twitter propose a button to return to the original app that redirects to "/twitter/authorized?denied=xxxx".
This calls the authorized method in oauth1.py. However, the fact that the redirect url only contains a denied key and does not have an oauth_token key causes self.session.parse_authorization_response(request.url) to crash.
Adding try except around self.session.parse_authorization_response(request.url) avoids this crash.
> Added try except to parse_authorization_response in oauth1

- docs/quickstarts/azure.rst
- docs/quickstarts/dropbox.rst
- docs/quickstarts/github.rst
- docs/quickstarts/google.rst
- docs/quickstarts/meetup.rst
- docs/quickstarts/nylas.rst
- docs/quickstarts/slack.rst
- docs/quickstarts/twitter.rst
- clarifying the purpose of OAUTHLIB_INSECURE_TRANSPORT
- "production" is less clear, use "local" or "trusted connection"
- add a few additional hints to the user about what's going on
> Clarifying github example docs - http/https

- docs/index.rst
- docs/testing.rst
It took me a while to figure out how to be able to test a Flask app that had some or all of its routes behind a login decorator mandating oauth2.
This is a write-up of what one could do. I'm hoping to get this accepted into flask-dance as I believe this would prove useful to others.
> docs: Add documentation on testing strategies

- .gitignore
- .gitmodules
- docs/install.rst
- tox.ini
I've added tox file to reproduce the TravisCI build and ReadTheDocs build, **before** pushing changes to GitHub.
At the moment, it does not support the `postgresql` build variant, because it implies to have a postgresql installed on the developer machine. However, we can consider adding it.
Also, the `tox -e docs` is reproducing the exact steps of readthedocs website, i.e. python2.7, and should help when proposing documentation changes in PR.
Why I have added this ? It allows upstream libraries e.g. `oauthlib` to run the `flask-dance` unit tests before releasing new `oauthlib` versions.
> Improve build mechanism

- flask_dance/contrib/google.py
- tests/contrib/test_google.py
Use the full scope. Something's changed on Google's side that now really requires the `OAUTHLIB_RELAX_TOKEN_SCOPE` to be set when using "short" scopes, for some reason that worked before without it. Since this is not extensively documented and the default now causes things to break, update the default to something that works without additional configuration/caveats.
Fixes #148
> google: Update default scope

- CHANGELOG.rst
- docs/quickstarts/azure.rst
- flask_dance/contrib/azure.py
Microsoft updated their api to be more "openid" compliant.  ( [v1-v2-comparison](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-compare) )
The graph scope "user.read" has been replaced by "User.Read" or "https://graph.microsoft.com/user.read". 
It is seems enough for personal accounts (like outlook.com), but openid scopes are needed for entreprise accounts ("openid", "profile", "email").
"User.Read" scope is still needed in order to get an access_token.
It is related to singingwolfboy/flask-dance#149 issue.
And I also updated the example in order to display the email in both cases (personal or enterprise account)
> Updated default scopes according to recent moves from Azure.

- CHANGELOG.rst
- flask_dance/contrib/google.py
- tests/contrib/test_google.py
Only when we request an offline token do we actually get a refresh token that can be used with the `auto_refresh_url` endpoint to refresh the token. As such, when we get an online token instead (the default) we shouldn't set `auto_refresh_url`.
This is the first part of the changes discussed in #143, #144 and just ensures that requests-oauthlib no longer tries to refresh an online token but immediately raises a `TokenExpiredError`. This does not constitute an API change since the resulting error is the same, but would at least result in a more clear traceback.
> google: Set auto_refresh_url only for offline

- CHANGELOG.rst
- docs/quickstarts/google.rst
- flask_dance/contrib/google.py
- tests/contrib/test_google.py
Adds a `hosted_domain` argument to `make_google_blueprint`. 
From Google OpenID Connect [docs](https://developers.google.com/identity/protocols/OpenIDConnect#hd-param):
>The hd (hosted domain) parameter streamlines the login process for G Suite hosted accounts. By including the domain of the G Suite user (for example, mycollege.edu), you can indicate that the account selection UI should be optimized for accounts at that domain.
Related to #165.
**Example:**
```python
blueprint = make_google_blueprint(
client_id="my-key-here",
client_secret="my-secret-here",
scope=["profile", "email"],
hosted_domain="example.com"
)
```
> Add Google hosted domain (hd) url parameter

- CHANGELOG.rst
- docs/providers.rst
- flask_dance/contrib/zoho.py
- tests/contrib/test_zoho.py
Creating a custom WebClient that supports the Zoho Oauth standard appears to be the only way to set headers for this provider.
> Initial commit for Zoho provider

- docs/quickstarts/sqla-multiuser.rst
Allow the sqlalchemy example to run out-of-the-box without modifications but clarify that model attributes are entirely up to the end-user and not Flask-Dance specific.
> docs:sqla: Allow functionality out-of-the-box

- flask_dance/contrib/zoho.py
Looks like it was a simple spacing issue causing the docs not to render correctly
> Fix spacing issue causing Zoho docs not to render correctly

- CHANGELOG.rst
- flask_dance/contrib/facebook.py
- tests/contrib/test_facebook.py
Prior to this change, if an existing user tried to login after refusing
an authorization scope, the dialog would just redirect him to sucess
without asking again for the missing scopes.
Sarting from this commit, using a flag and as documented
[here](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#reaskperms) a blueprint can be set to re-request the declined scopes
> Add option for facebook blueprint to rerequest authorization

- README.rst
It's getting long (yay!), and should be autogenerated in the docs.
> Remove provider list from README

- tests/consumer/storage/test_sqla.py
This suppresses the following warnings when running tests:
```
tests/consumer/storage/test_sqla.py::test_sqla_cache
.../flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
```
> Suppress some SQLAlchemy warnings

- CHANGELOG.rst
- README.rst
- docs/api.rst
- flask_dance/consumer/requests.py
- tests/consumer/test_oauth1.py
- tests/consumer/test_oauth2.py
This allows you to decorate views to indicate that the user must have an OAuth token to continue. It should automatically be available on every session proxy, including all the pre-set configurations.
> Add `authorization_required` decorator on session

- setup.py
```
Warning: 'classifiers' should be a list, got type 'tuple'
```
> Fix a warning in setup.py

- CHANGELOG.rst
- docs/signals.rst
- flask_dance/__init__.py
- flask_dance/consumer/__init__.py
- flask_dance/consumer/base.py
- flask_dance/consumer/oauth1.py
- flask_dance/consumer/oauth2.py
- tests/consumer/test_oauth1.py
- tests/consumer/test_oauth2.py
Implement `before_authorized` signal to allow custom methods to run before the initial network redirection (in the `login` method). closes #219.
> add before_login signal to allow custom actions before first redirect

- CHANGELOG.rst
- flask_dance/contrib/google.py
- tests/contrib/test_google.py
Adding the possibility to reprompt the select account page with Google OAuth.
Please see the new documentation for 'prompt' [here](https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters)
resolves #227
> Google OAuth prompt update

- docs/testing.rst
Looks to me that a `not` has been forgotten here.
> doc: fix github example

- docs/understanding-the-magic.rst
This PR is just a suggestion, and I'm sure it could be worded better.
I was trying to verify that Flask-Dance correctly followed the Google OpenID documents ( https://developers.google.com/identity/protocols/OpenIDConnect - see "Authentication URI parameters" -> "state" -> "(Optional, but strongly recommended)" ).
I had a heck of a time tracking down the code path across three packages (flask-dance -> requests_oauth -> oauthlib) to finally find the function where the `state` variable is initialized by default. I couldn't find it documented anywhere, and it struck me as something that should be called out given the "Optional but strongly recommended" call out by Google.
I'm happy to rework this, and would suggest that `nonce` get a callout here as well, perhaps?
> Proposal: call out default `state` variable in docs

- docs/multi-user.rst
This adds clarification in the multi-user setup part of the documentation on how to override Flask-Dance default behaviour. In my application, I had to redirect the user to a dynamic url after creating his account, however I didn't understand how I could redirect the user and return False from the signal at the same time. I think this clarifies it. 
resolves #270
> Adding Response object explanation to multi-user setup.

- flask_dance/contrib/README.rst
There is a small typo in flask_dance/contrib/README.rst.
Should read `criteria` rather than `critera`.
Hope this PR meets your criteria.
> docs: Fix simple typo, critera -> criteria

- CHANGELOG.rst
- docs/providers.rst
- docs/spelling_wordlist.txt
- flask_dance/contrib/digitalocean.py
- tests/contrib/test_digitalocean.py
- add digitalocean.py to configure blueprint for provider
- add tests for Digital Ocean provider
- update CHANGELOG
- update docs/providers.rst
- add DigitalOcean to wordlist
Question:
The default scope with Digital Ocean is `read`. I left the default as `None` for library consistency, would it make sense in this case to change the default, or is this something we want the user to explicitly set?
> Add Digital Ocean as a provider

- .github/workflows/test.yml
By default, `coverage run` does not generate a `coverage.xml`, you have to call `coverage xml` for that. Since we're not doing that, `coverage.xml` doesn't exist so we don't end up uploading code coverage.
It turns out however that doing this is unnecessary. The codecov action will do this by itself if it has to, as long as it finds a `.coverage` which coverage.py will write to by default.
> test: Fix codecov reporting

- flask_dance/contrib/dropbox.py
- tests/contrib/test_dropbox.py
This is built on top of @thunderkeys work done in #332 . 
Changes when compared to #332 
* removed unrelated OAuth2Session change
* changed URL to dropbox documention - the previous page didn't mention "offline" option
* added test & refactored old one a little bit to reduce code duplication
> Add support for Dropbox short-lived offline refresh tokens

- CHANGELOG.rst
- docs/providers.rst
- flask_dance/contrib/atlassian.py
- flask_dance/contrib/jira_oauth2.py
- tests/contrib/test_atlassian.py
According to https://www.atlassian.com/migration/faqs#general, Atlassian stopped selling and is going to stop maintaining server products and focus on cloud products which use Oauth2 authentication to allow external applications and services to access Atlassian product APIs.
Please suggest naming changes since there already is jira (oauth1) plugin.
> Implemented atlassian blueprint for oauth2

- CHANGELOG.rst
- flask_dance/contrib/salesforce.py
- tests/contrib/test_salesforce.py
Right now Salesforce will be working only with the production instance. That change adds the possibility to specify custom domains in the Salesforce blueprint. 
Also changed base URL in the blueprint. It will make easier to use the session in further requests.
> Added domain option to Salesforce blueprint

- CHANGELOG.rst
- flask_dance/contrib/gitlab.py
- tests/contrib/test_gitlab.py
Due to the additional setup in this function, it is preferable to use `make_gitlab_blueprint` instead of creating a `Oauth2CustomerBlueprint` directly. However, in the event of a self-hosted gitlab instance using self-signed certificates, these certificates cannot always be verified and this makes the redirection result in an SSL verification error. Thus, one is unable to use `make_gitlab_blueprint` and must instead use the "raw" `Oauth2CustomerBlueprint` in order to pass `token_url_params=dict(verify=False)`.
This change is to add the ability to forward kwargs from `make_gitlab_blueprint` into `Oauth2CustomerBlueprint` for more customisationof functionality.
> Send specific kwargs to Oauth2CustomerBlueprint

- flask_dance/consumer/base.py
- flask_dance/consumer/oauth1.py
- flask_dance/consumer/oauth2.py
- flask_dance/contrib/authentiq.py
- flask_dance/contrib/azure.py
- flask_dance/contrib/digitalocean.py
- flask_dance/contrib/discord.py
- flask_dance/contrib/dropbox.py
- flask_dance/contrib/facebook.py
- flask_dance/contrib/github.py
- flask_dance/contrib/gitlab.py
- flask_dance/contrib/google.py
- flask_dance/contrib/heroku.py
- flask_dance/contrib/jira.py
- flask_dance/contrib/linkedin.py
- flask_dance/contrib/meetup.py
- flask_dance/contrib/nylas.py
- flask_dance/contrib/reddit.py
- flask_dance/contrib/slack.py
- flask_dance/contrib/spotify.py
- flask_dance/contrib/strava.py
- flask_dance/contrib/twitter.py
- flask_dance/contrib/zoho.py
- tests/consumer/test_oauth1.py
- tests/consumer/test_oauth2.py
- tests/contrib/test_google.py
- tests/contrib/test_jira.py
Having a multi-tenant site (based on the host name) requires that you use the "host" on the rule (by passing the "host" parameter to the add_url_rule call).  Secondly your Flask app needs to set host_matching to True and set static_host to the "main" host.  There are additional tricks around this, but the answer at https://stackoverflow.com/questions/51883773/flask-app-that-routes-to-multiple-top-level-and-sub-domains given a good indication of what is required.
Currently in flask-dance these rules are created from within BaseOAuthConsumerBlueprint in a rather hard-coded manner with no possibility to add parameters such as "host".
To pass in additional parameters, each make_*_blueprint is now able to take additional parameters (in the form of the rule_kwargs dict) and pass them down (via …
> #357 Add the possibility to add kwargs such as "host" from make*blueprint calls

- .github/workflows/test.yml
- CHANGELOG.rst
- flask_dance/consumer/base.py
- requirements.txt
We should verify that we _actually_ support the lowest version of Flask that we claim to support. That means running the automated tests with that version.
I discovered that the latest version of `pytest` doesn't run with Flask 0.7 anymore, which is why I'm bumping up the minimum supported version to Flask 1.0.4. I believe this is due to [this Flask pull request](https://github.com/pallets/flask/issues/3275).
Since we are changing the minimum version of Flask that we support, this will require a major version bump.
> install specific Flask version for tests

- CHANGELOG.rst
- flask_dance/consumer/base.py
- flask_dance/consumer/oauth1.py
- flask_dance/consumer/oauth2.py
- flask_dance/contrib/atlassian.py
- flask_dance/contrib/authentiq.py
- flask_dance/contrib/azure.py
- flask_dance/contrib/digitalocean.py
- flask_dance/contrib/discord.py
- flask_dance/contrib/dropbox.py
- flask_dance/contrib/facebook.py
- flask_dance/contrib/github.py
- flask_dance/contrib/gitlab.py
- flask_dance/contrib/google.py
- flask_dance/contrib/heroku.py
- flask_dance/contrib/jira.py
- flask_dance/contrib/linkedin.py
- flask_dance/contrib/meetup.py
- flask_dance/contrib/nylas.py
- flask_dance/contrib/reddit.py
- flask_dance/contrib/salesforce.py
- flask_dance/contrib/slack.py
- flask_dance/contrib/spotify.py
- flask_dance/contrib/strava.py
- flask_dance/contrib/twitch.py
- flask_dance/contrib/twitter.py
- flask_dance/contrib/zoho.py
See https://www.python.org/dev/peps/pep-3102/. I intended to use this feature when I first created this library, but Python 2.7 compatibility prevented me from doing so, and I forgot about it until recently. Since this has the potential of causing backwards-incompatibility, we will need to bump the major version number.
@daenney, do you have any thoughts about this change?
> use keyword-only arguments

- .github/workflows/test.yml
- requirements.txt
- tests/consumer/storage/test_sqla.py
- tests/consumer/test_oauth1.py
- tests/consumer/test_oauth2.py
[Flask 2.1.0 has the following changelog entry](https://flask.palletsprojects.com/en/2.1.x/changes/#version-2-1-0):
> From Werkzeug, for redirect responses the Location header URL will remain relative, and exclude the scheme and domain, by default.
This fixes the tests to account for that. In the process of doing so, I discovered that older versions of Flask no longer install and run correctly, due to unconstrained dependency definitions. As a result, this project will no longer support those versions of Flask.
> fix tests and adjust dependencies

- flask_dance/consumer/base.py
- flask_dance/consumer/oauth1.py
- flask_dance/consumer/oauth2.py
- flask_dance/consumer/requests.py
- flask_dance/utils.py
This is #375 rebased onto the latest `main` branch.
> use `del obj.name` as invalidate_cached_property is deprecated

- .coveragerc
- flask_dance/consumer/base.py
- flask_dance/utils.py
- tests/consumer/test_oauth1.py
- tests/consumer/test_oauth2.py
We haven't officially supported Python 2 in awhile. These imports for Python 2 need to go.
> Drop py2 imports

- CHANGELOG.rst
- docs/providers.rst
- flask_dance/contrib/orcid.py
- tests/contrib/test_orcid.py
This PR adds support for ORCID (https://orcid.org/) and its sandbox server (https://sandbox.orcid.org) via a blueprint init option `use_orcid_sandbox`.
It is slightly tricky to test this as OAuth configs at ORCID require human intervention at ORCID's end, and even then, the ORCID sandbox does not allow non-HTTPS callback URIs (like localhost). I was able to use this code to authorize via the ORCID sandbox by monkey-patching the authorized URL in the base blueprint to point at [Google's OAuth playground](https://developers.google.com/oauthplayground/)  using the `openid` scope (might be useful if this was easier to do).
Thanks for flask-dance!
> Add ORCID OAuth2 provider
