CHANGELOG.rst, flask_dance/consumer/oauth2.py
To make it easier to diagnose issues
=> Adding debug logging

CHANGELOG.rst, flask_dance/consumer/oauth2.py
This is useful for an upcoming Slack integration.
=> Allow setting an auth property after blueprint creation

.gitignore, CHANGELOG.rst, README.rst, docs/providers.rst, docs/quickstarts/index.rst, docs/quickstarts/slack.rst, flask_dance/contrib/slack.py, tests/contrib/test_slack.py
[Slack](https://slack.com/) is cool, and [Slack bots](https://api.slack.com/) are also cool.
=> Added Slack integration

docs/quickstarts/sqla-multiuser.rst
Solved simply by removing the parenthesis (converting function call to attribute access).
=> Fixes singingwolfboy/flask-dance#48

.gitignore, tests/consumer/storage/test_sqla.py
Not sure why this was off; maybe something changed in a dependency?
=> Correct query counts in tests

CHANGELOG.rst, README.rst, docs/providers.rst, docs/quickstarts/azure.rst, docs/quickstarts/index.rst, flask_dance/__init__.py, flask_dance/contrib/azure.py, tests/contrib/test_azure.py
Hello,
I currently have project which needs an authentication with Azure AD and the v2.0 endpoint. So, I decided to create a new pre-set.
Regards,
Steven.
=> Added the Azure AD pre-set configuration

dev-requirements.txt, flask_dance/consumer/backend/session.py, flask_dance/consumer/base.py, flask_dance/consumer/requests.py, flask_dance/utils.py, requirements.txt, tests/consumer/test_oauth1.py, tests/consumer/test_oauth2.py
While testing Flask-Dance with Bitbucket, I found that the OAuth2 auto token refresh wasn't working properly. I believe this makes it work right.
=> Improvements for OAuth2 auto refresh

docs/index.rst, docs/install.rst
=> Add install docs

CHANGELOG.rst, flask_dance/contrib/dropbox.py
Forgot to update after copy-paste, I suppose
=> Fix docstring for make_dropbox_blueprint

CHANGELOG.rst, README.rst, docs/providers.rst, flask_dance/contrib/nylas.py, tests/contrib/test_nylas.py
=> Added Nylas configuration

CHANGELOG.rst, docs/providers.rst, flask_dance/__init__.py, flask_dance/contrib/spotify.py, tests/contrib/test_spotify.py
Hi @singingwolfboy! I found out about `Flask-Dance` last night. It's a really great framework, nice work.
I'm working on a project using Spotify's APIs. Instead of keeping the provider implementation as custom, I figured to contribute it back upstream. I still need to add docs, but wanted to open this PR sooner than later, so I can stop using my fork in my requirements file.
Please let me know if there's anything you'd like me to change. Happy to include docs in this PR or follow-up separately. I didn't see a `CONTRIBUTING` file so I hope I'm adding a provider correctly and didn't miss anything (besides docs, heh).
=> Add Spotify provider

.gitignore, flask_dance/consumer/backend/sqla.py, flask_dance/consumer/base.py, flask_dance/consumer/oauth1.py, flask_dance/consumer/oauth2.py, flask_dance/consumer/requests.py
Here are just some ideas for comments that I think might make it easier for future users to understand how everything works. I'm open to changing things (e.g. moving explanations into the docs, or changing the way things are explained). But I think those functions really could benefit from being explained in-depth.
=> Add to the documentation

.gitignore, docs/quickstarts/azure.rst, docs/quickstarts/dropbox.rst, docs/quickstarts/github.rst, docs/quickstarts/google.rst, docs/quickstarts/meetup.rst, docs/quickstarts/nylas.rst, docs/quickstarts/slack.rst, docs/quickstarts/twitter.rst, docs/signals.rst, flask_dance/consumer/backend/sqla.py, flask_dance/consumer/base.py, flask_dance/consumer/oauth1.py, flask_dance/consumer/oauth2.py, flask_dance/consumer/requests.py, flask_dance/contrib/slack.py, flask_dance/utils.py
Just some more ideas, obviously feel free to keep whatever's helpful and discard the rest.
- Just as a heads up, I'm a little nervous that my suggested session-related comments are not accurate.
- Also, I removed imports that PyCharm said were unused, so that's how I did that. It might not be right.
=> Documentation

docs/backends.rst
=> Typo fix in backend rst

docs/index.rst, docs/multi-user.rst, docs/quickstarts/sqla-multiuser.rst
Provide better documentation for multi-user setups, and update the existing documentation to account for the `user_required` change introduced in #92. Issue raised by #100.
=> Multi-user docs

tests/consumer/test_requests.py
requests-oauthlib 0.5 has been out for awhile
=> Disable requests-oauthlib version checks

docs/quickstarts/sqla-multiuser.rst
Fixes a typo in the multi user SQLA quick start code
=> Fixes #118

CHANGELOG.rst, docs/providers.rst, flask_dance/contrib/okta.py, tests/contrib/test_okta.py
Was exploring using Okta for a project, came across Flask-Dance, decided to add support for it.
=> Added Okta support

docs/conf.py, docs/index.rst, docs/logout.rst
Since logging out seems to be a problem for several people (see #145), here's some documentation describing the options.
@daenney, can you review this and let me know it it's understandable? Is there anything I'm missing?
=> Add documentation for how to log out a user

CHANGELOG.rst, docs/providers.rst, flask_dance/contrib/reddit.py, tests/contrib/test_reddit.py
I'm using Flask Dance for my Reddit-related project, so decided to extract my custom Reddit conf.
Unfortunately, I'm pretty new to pytest and oauthlib, so I'm not sure how to achieve 100% coverage.
It seems that one statement in my custom session is still missed.
=> Add Reddit pre-set configuration

docs/proxies.rst
* Explain which headers are necessary
* Explain how to properly access those headers
* Point to Flask's documentation on how to configure HTTPS proxies
instead of maintaining our own, and potentially outdated
instructions
Closes #188
=> docs: Rewrite the Proxies and HTTPS

flask_dance/contrib/zoho.py
Blank line ensures the docstrings get parsed correctly by sphinx.
=> Fixed the formating so the first args are formated correctly

flask_dance/consumer/requests.py
https://github.com/oauthlib/oauthlib/pull/546
=> Use public oauthlib method

CHANGELOG.rst, docs/providers.rst, flask_dance/contrib/authentiq.py, tests/contrib/test_authentiq.py
This adds pre-configured support for [Authentiq](https://www.authentiq.com/), and also sorts the longish list of providers.
=> Add pre-set configuration for Authentiq

.travis.yml
Hopefully this will fix the test failure...
=> Upgrade pytest on Travis CI

docs/examples.rst, docs/index.rst
Follow up to #202. @headwinds, how does this look to you?
=> Add a list of projects that use Flask-Dance

tests/consumer/test_oauth1.py, tests/consumer/test_oauth2.py
=> Fix Werkzeug ProxyFix issue

CHANGELOG.rst, docs/providers.rst, flask_dance/contrib/linkedin.py, tests/contrib/test_linkedin.py
=> Add LinkedIn pre-set configuration

CHANGELOG.rst, flask_dance/contrib/meetup.py
=> Meetup: include_client_id=True

tests/requirements.txt, tox.ini
P.S.: Thanks for the great talk @ flaskcon :-)
=> Fix broken tox tests

flask_dance/consumer/requests.py, flask_dance/consumer/storage/sqla.py
- Newer black versions is pickier, this solves one problem.
=> Fix for newer black.

CHANGELOG.rst, docs/providers.rst, docs/spelling_wordlist.txt, flask_dance/contrib/strava.py, tests/contrib/test_strava.py
- Add Strava as Oauth2 supplier.
=> Add Strava.

flask_dance/contrib/discord.py, tests/contrib/test_discord.py
As documented [here](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant-authorization-url-example) this would be good to get implemented.
=> Added Discord prompt param

CHANGELOG.rst, docs/providers.rst, flask_dance/contrib/salesforce.py, tests/contrib/test_salesforce.py
=> Implemented salesforce oauth2 blueprint

flask_dance/contrib/gitlab.py, tests/contrib/test_gitlab.py, tests/requirements.txt
=> fix tests for gitlab tls verification

CHANGELOG.rst, docs/providers.rst, flask_dance/contrib/twitch.py, tests/contrib/test_twitch.py
=> Twitch configuration

pyproject.toml
Hey @daenney, I should have done this awhile ago, but better late than never, I suppose! Would you like to be in the `pyproject.toml` file as a maintainer for the project? And if so, which email would you like to use? (It will be public!)
=> add @daenney as official maintainer

flask_dance/consumer/base.py, pyproject.toml, tests/consumer/storage/test_sqla.py, tests/consumer/test_oauth1.py, tests/consumer/test_oauth2.py, tests/contrib/test_gitlab.py, tests/contrib/test_slack.py
=> fix tests for werkzeug 3

CHANGELOG.rst, flask_dance/contrib/azure.py, tests/contrib/test_azure.py
This PR adds the capability of automatic token refresh to the azure bindings.
=> Enable token refresh for azure
